spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    generate-ddl: true

  application:
    name: backend-skeleton-service

logging:
  level:
    org:
      springframework:
        web:
          filter: DEBUG
      hibernate:
        SQL=DEBUG:
